# .github/workflows/exploration-matrix.yml
name: Exploration Spatiale Optimisée

on:
  push:
    branches:
      - main

jobs:
  exploration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mission:
          - nom: Mars
            equipements: "Rover, Combinaison spatiale"
            duree: "7 mois"
            activite: "Analyse des roches"
            type: "planete"
          - nom: Lune
            equipements: "Module lunaire, Combinaison spatiale"
            duree: "3 jours"
            activite: "Collecte d'échantillons"
            type: "satellite"
          - nom: Vénus
            equipements: "Sonde atmosphérique, Instruments scientifiques"
            duree: "5 mois"
            activite: "Analyse atmosphérique"
            type: "planete"

    name: Mission ${{ matrix.mission.nom }}
    steps:
      - run: |
          echo "=== Mission ${{ matrix.mission.nom }} ==="
          echo "Équipements : ${{ matrix.mission.equipements }}"
          echo "Durée du voyage : ${{ matrix.mission.duree }}"
          echo "Activité principale : ${{ matrix.mission.activite }}"
          echo "Type de destination : ${{ matrix.mission.type }}"
          echo "=== Fin de la mission ==="


  demandes_president:
    needs: exploration  # Ce job attend la fin du job "exploration"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mission: [Mars, Lune, Vénus]
        include:
          - mission: Mars
            equipement_special: "Space Burger"
            commentaire: "Pour maintenir le moral de l'équipage"
          - mission: Lune
            equipement_special: "Télescope pour observer les aliens"
            commentaire: "Parce que les aliens existent, c'est sûr !"
          - mission: Vénus
            # Pas de valeurs spéciales = test des valeurs par défaut

    name: Demandes Présidentielles - ${{ matrix.mission }}
    steps:
      - run: |
          echo "=== Demandes Présidentielles - Mission ${{ matrix.mission }} ==="
          echo "Équipement spécial : ${{ matrix.equipement_special || 'Pas besoin' }}"
          echo "Commentaire : ${{ matrix.commentaire || 'Aucun commentaire' }}"
          echo "=== Fin ==="