# .github/workflows/exploration-repetitive.yml
name: Exploration Spatiale Répétitive

on:
  push:
    branches:
      - main

jobs:
  mission-mars:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "=== Mission Mars ==="
          echo "Équipements : Rover, Combinaison spatiale"
          echo "Durée du voyage : 7 mois"
          echo "Activité principale : Analyse des roches"
          echo "Type de destination : planete"
          echo "=== Fin de la mission ==="

  mission-lune:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "=== Mission Lune ==="
          echo "Équipements : Module lunaire, Combinaison spatiale"
          echo "Durée du voyage : 3 jours"
          echo "Activité principale : Collecte d'échantillons"
          echo "Type de destination : satellite"
          echo "=== Fin de la mission ==="

  mission-venus:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "=== Mission Vénus ==="
          echo "Équipements : Sonde atmosphérique, Instruments scientifiques"
          echo "Durée du voyage : 5 mois"
          echo "Activité principale : Analyse atmosphérique"
          echo "Type de destination : planete"
          echo "=== Fin de la mission ==="

  demandes_president:
    needs: exploration  # Ce job attend la fin du job "exploration"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mission: [Mars, Lune, Vénus]
        include:
          - mission: Mars
            equipement_special: "Space Burger"
            commentaire: "Pour maintenir le moral de l'équipage"
          - mission: Lune
            equipement_special: "Télescope pour observer les aliens"
            commentaire: "Parce que les aliens existent, c'est sûr !"
          - mission: Vénus
            # Pas de valeurs spéciales = test des valeurs par défaut

    name: Demandes Présidentielles - ${{ matrix.mission }}
    steps:
      - run: |
          echo "=== Demandes Présidentielles - Mission ${{ matrix.mission }} ==="
          echo "Équipement spécial : ${{ matrix.equipement_special || 'Pas besoin' }}"
          echo "Commentaire : ${{ matrix.commentaire || 'Aucun commentaire' }}"
          echo "=== Fin ==="
