name: Gestion des reptiles

on:
  push:
    branches:
      - main
    paths:
      - 'reptiles/**'

  pull_request:
    branches:
      - main
    types: [opened, edited, synchronize]
    paths:
      - 'zoo/reptiles/**'

jobs:
  gestion-reptiles:
    runs-on: ubuntu-latest
    steps:
      - name: Push - ajout reptile
        if: github.event_name == 'push'
        run: |
          echo "Un reptile a été ajouté au zoo"
      
      - name: PR - reptile proposé
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        run: |
          echo "Un nouveau reptile est proposé !"

      - name: PR - reptile modifié
        if: github.event_name == 'pull_request' && github.event.action == 'edited'
        run: |
          echo "Les informations d'un reptile ont été modifiées"

      - name: PR - reptile synchronisé
        if: github.event_name == 'pull_request' && github.event.action == 'synchronize'
        run: |
          echo "Un reptile a été mis à jour avec de nouvelles informations"