name: Soins des mammifères

on: 
  push:
    branches:
      - main

    paths:
      - 'zoo/mammiferes/**'

jobs:
  soins-mammiferes:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher les informations du commit
        run: |
          echo "Message : ${{ github.event.head_commit.message }}"
          echo "Type d'événement : ${{ github.event_name }}"
          echo "Auteur : ${{ github.actor }}"